# This is a basic workflow to help you get started with Actions

name: Linux C/C++ Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc hello.c -o hello.out
    - name: Run
      run: ./hello.out
